CREATE TABLE IF NOT EXISTS urls (
    id SERIAL PRIMARY KEY,
    original_url TEXT NOT NULL,
    short_code VARCHAR(10) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT now(),
    custom_alias BOOLEAN DEFAULT FALSE
);
ALTER TABLE urls ALTER COLUMN short_code TYPE VARCHAR(50);